on: ["push", "pull_request"]

name: CI/CD

jobs:
  build:
    name: Build, tests and coverage
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: |
          rm -rf examples
          npm install

      - name: npm build and tests
        run: |
          npm test
          npm run build

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
