on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  build:
    name: Build, tests and coverage
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: npm build and tests
        run: |
          npm run build
          npm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
